name: freezed_tutorial
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:

  freezed: ^0.10.4
  json_serializable: ^3.3.0
  build_runner: ^1.8.1
dependencies:  
  meta: ^1.1.8
  json_annotation: ^3.0.1
  freezed_annotation: ^0.7.1
